### ISSUE TITLE
Librarie dependency problem

### ISSUE THREAD

**Issue by alcalyn** [ezsystems/EzSystemsPrivacyCookieBundle#10]
We cannot use this bundle out of the box.

I get this error:

```
Attempted to load class "Configuration" from namespace "eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\SiteAccessAware"
```

So this bundle needs `eZ\Bundle\EzPublishCoreBundle` to work, and it is not in `composer.json`.

Either this bundle is part of the whole eZ CMS, or Configuration class should not extends SiteAccessConfiguration, but just implement `Symfony\Component\Config\Definition\ConfigurationInterface` in order to work out of the box.

**Comment by bdunogier** [comment]
You are right, @alcalyn. The siteaccess aware part should be moved to one of the eZ Platform packages.

@clash82 could we try to make this happen ? :-)

**Comment by clash82** [comment]
@bdunogier Second approach looks good for me. Solution should appear in next days. Thanks for reporting this issue @alcalyn.

**Comment by clash82** [comment]
It's on our todo list https://jira.ez.no/browse/EZP-25386
thanks @alcalyn
