### ISSUE TITLE
Symfony 3 compatibility

### ISSUE THREAD

**Issue by Laurent3170** [ezsystems/EzSystemsPrivacyCookieBundle#11]
Hi,
I have tried to install your bundle, but... As I am using symfony 3 it breaks as your composer.json require `"symfony/symfony": "~2.6"`.
Is it compatible with symfony 3 ? if not, will it be ?
Thanks

**Comment by SylvainGuittard** [comment]
Hi @Laurent3170 !

For now, eZ Publish Platform and eZ Platform are not compatible with Symfony 3.
https://github.com/ezsystems/ezplatform/blob/master/composer.json#L21
We'll update this bundle when the previous softwares will support Symfony 3.

Are you using eZ Publish Platform or eZ Platform?

**Comment by Laurent3170** [comment]
Thanks for your answer.
No I'm not doing eZ Publish, neither eZ Platform

**Comment by clash82** [comment]
Hi @Laurent3170,
unfortunately this bundle currently requires eZ Publish/Platform to work but we are planning to make it more independent in the near future.

**Comment by Laurent3170** [comment]
Ok, I'll try to find another one :-(

**Comment by bdunogier** [comment]
Actually, @Laurent3170, it turns out that making it independent from eZ Platform might be easier than expected. @clash82 will try to have a look.

Then if we don't have a dependency on ezpublish-kernel, it shouldn't be a problem to make the bundle Sf 3.0 compatible.

**Comment by Laurent3170** [comment]
It sounds great bu I have found a small js who does the job as needed and simply. But thanks anyway.

**Comment by bdunogier** [comment]
No problem :-)

See you around !
