### ISSUE TITLE
Uncaught ReferenceError: eZ is not defined

### ISSUE THREAD

**Issue by Iraldoad** [ezsystems/EzSystemsPrivacyCookieBundle#13]
I tried to make use of the bundle and shows me this error in the browser console. eZ is not defined.

**Comment by clash82** [comment]
Hi @Iraldoad, assets are not loaded correctly.

Please, make sure you added `bundles/ezsystemsprivacycookie/js/privacycookie.js` to your project (eg. https://github.com/ezsystems/DemoBundle/blob/master/Resources/views/page_head_script.html.twig#L21) and installed assets using `app/console assets:install --symlink`.

On the `prod` environment you should also execute `app/console assetic:dump -e=prod` after all the above steps.

If this will not help, ping me again :)

**Comment by Iraldoad** [comment]
Hello,
I did all these steps, and I am using the dev environment, but it also probe into the prod environment. Also load jQuery before script bundle.

**Comment by clash82** [comment]
This extension doesn't need jQuery to work.

Issue is related to missing `privacycookie.js` file. Can you check if this file is included on the list of all loaded js libs in your header template? Please check if you have access to read this file from the browser window.

**Comment by Iraldoad** [comment]
I checked and all that. Js and css files are accessible by the browser. I need some specific configuration on the config.yml?

![css](https://cloud.githubusercontent.com/assets/15159678/15709991/cdff8414-27d5-11e6-9654-b39f1e8472ed.png)
![js](https://cloud.githubusercontent.com/assets/15159678/15709990/cdfd1ddc-27d5-11e6-9bda-679fa383c7eb.png)

**Comment by Iraldoad** [comment]
The error is here:

// privacycookie.html.twig :22
(function() {
        var privacyCookieBanner = new eZ.PrivacyCookieBanner({
        cookieName: 'privacyCookieAccepted',
        days: 365
    });
    .
    .
    .
}) ();

**Comment by clash82** [comment]
Specific configuration is not required here.

Maybe it's something with your browser's cache?
Can you clear the cache and try again?

**Comment by Iraldoad** [comment]
Yes, I have cleared the cache on several occasions.

**Comment by clash82** [comment]
Have you tried with different browser?

**Comment by Iraldoad** [comment]
Yes, I tried the Firefox browser. 

----- Mensaje original -----

De: "Rafał Toborek" <notifications@github.com> 
Para: "ezsystems/EzSystemsPrivacyCookieBundle" <EzSystemsPrivacyCookieBundle@noreply.github.com> 
CC: "Iraldo Arévalo Delfín" <iraldo@uci.cu>, "Mention" <mention@noreply.github.com> 
Enviados: Jueves, 2 de Junio 2016 9:48:26 
Asunto: [MASSMAIL] Re: [ezsystems/EzSystemsPrivacyCookieBundle] Uncaught ReferenceError: eZ is not defined (#13) 



Have you tried with different browser? 

— 
You are receiving this because you were mentioned. 
Reply to this email directly, view it on GitHub , or mute the thread . 




-- 
Ing. Iraldo Arévalo Delfín 
Centro de Identificación y Seguridad Digital 
Universidad de las Ciencias Informáticas 
Teléfono: 53-53609029

**Comment by clash82** [comment]
Are you using regular Symfony app (what version?) or eZ Publish/Platform?

**Comment by Iraldoad** [comment]
I'm using Symfony Standard Edition, version 2.7.

**Comment by Iraldoad** [comment]
Apparently the object eZ not being created in:

// privacycookie.js
(function (global, doc) {
    var eZ = global.eZ = global.eZ || {};
   .
   .
   .
}

**Comment by clash82** [comment]
Last question... what version on PrivacyCookieBundle are you using?

**Comment by clash82** [comment]
I've just test it on `sf 2.7.13` without issues.

I'm using `v1.0.0-beta3` version of `PrivacyCookieBundle`.

Installation steps:

- add assets to base.html.twig file:

```twig
{% javascripts
    'bundles/ezsystemsprivacycookie/js/privacycookie.js'
%}
    <script type="text/javascript" src="{{ asset_url }}"></script>
{% endjavascripts %}

{% stylesheets filter='cssrewrite'
    'bundles/ezsystemsprivacycookie/css/privacycookie.css'
%}
    <link rel="stylesheet" type="text/css" href="{{ asset_url }}"/>
{% endstylesheets %}
```

- enable bundle in `AppKernel.php` file:

```php
$bundles = array(
    ...
    new AppBundle\AppBundle(),
    new EzSystems\PrivacyCookieBundle\EzSystemsPrivacyCookieBundle()
);
```

- install assets:

```bash
app/console assets:install --symlink
```

- place Twig helper in base.html.twig file:

```twig
...
<body>
    {% block body %}{% endblock %}
    {% block javascripts %}{% endblock %}

    {{ show_privacy_cookie_banner('http://google.com') }}
</body>
```

**Comment by Iraldoad** [comment]
Problem solved. Thank you for your attention.
