### ISSUE TITLE
Symfony 3 compatibility

### ISSUE THREAD

**Issue by odecharette** [ezsystems/EzSystemsPrivacyCookieBundle#14]
Hello!

Thanks for this bundle
Could you make it compatible with SF 3 ?

Many thanks
Olivia

**Comment by clash82** [comment]
Hello @odecharette,

I'm glad that this bundle is helpful for you.
I will have look this week and try to improve compatibility with sf3.

**Comment by clash82** [comment]
@odecharette bundle was updated, you can test sf3 compatibility in https://github.com/ezsystems/EzSystemsPrivacyCookieBundle/tree/v1.0.0-beta5
