### ISSUE TITLE
Parameter list and examples in readme.md seems wrong

### ISSUE THREAD

**Issue by bedo-abn** [ezsystems/EzSystemsPrivacyCookieBundle#16]
'days' and 'bannerCaption' don't produce expected result. instead using 'cookieValidity' and  'caption' will do it.

**Comment by clash82** [comment]
Hello @bedo-abn and thank you for reporting the issue.
I guess no one ever used those settings...
I will have a look this week in fix it.

**Comment by bedo-abn** [comment]
hi, im new to github i tried to fork-branch-update-pull request... hope i didn't mess it up
