### ISSUE TITLE
Catchable Fatal Error on construct

### ISSUE THREAD

**Issue by nlescure** [ezsystems/EzSystemsPrivacyCookieBundle#4]
Hello,

For information, I've just updated from e93f0af to 6f794ee, and now, I have an error : 

ContextErrorException: Catchable Fatal Error: Argument 2 passed to EzSystems\PrivacyCookieBundle\Twig\PrivacyCookieTwigExtension::__construct() must be an instance of EzSystems\PrivacyCookieBundle\Banner\Banner, instance of EzSystems\PrivacyCookieBundle\Factory\ConfigurationBasedBannerFactory given, called in /var/www/xxxxx/ezpublish/cache/dev/ezpublishDevDebugProjectContainer.php on line 2023 and defined in /var/www/xxxxxx/vendor/ezsystems/privacy-cookie-bundle/Twig/PrivacyCookieTwigExtension.php line 29

It seems related to https://github.com/ezsystems/EzSystemsPrivacyCookieBundle/pull/3.

Standard call in the pagelayout : {{ show_privacy_cookie_banner('http://ez.no/Privacy-policy') }}

Am I the only one with this problem ?

**Comment by clash82** [comment]
Hi @nlescure,

I'll check what is wrong and give you a feedback.

**Comment by nlescure** [comment]
More information : eZ Publish 2014.11 (Symfony 2.5.10)

**Comment by andrerom** [comment]
@nlescure is the issue there after clearing symfony cache the brute force way? (`rm -Rf ezpublish/cache/dev/*`)

**Comment by nlescure** [comment]
@andrerom I was afraid when I saw your comment... But, yes, the problem si still here.

**Comment by nlescure** [comment]
DI problem ? 
In the ezpublishDevDebugProjectContainer.php

I can see : 

    /**
     * Gets the 'ez_privacy_cookie.twig.extension' service.
     *
     * This service is shared.
     * This method always returns the same instance of the service.
     *
     * @return \EzSystems\PrivacyCookieBundle\Twig\PrivacyCookieTwigExtension A EzSystems\PrivacyCookieBundle\Twig\PrivacyCookieTwigExtension instance.
     */
    protected function getEzPrivacyCookie_Twig_ExtensionService()
    {
        return $this->services['ez_privacy_cookie.twig.extension'] = new \EzSystems\PrivacyCookieBundle\Twig\PrivacyCookieTwigExtension($this->get('ez_privacy_cookie.banner_options'), $this->get('ez_privacy_cookie.configuration_banner_factory'));
    }

**Comment by andrerom** [comment]
Ok clear then, so @clash82 could you make sure to update the service definition to reflect what the class expect or the other way around? Should also add some more tests to this repo, to catch these kind of issues you'd need a few behat specs to verify it is loaded and working like expected.

**Comment by clash82** [comment]
@nlescure Could you please try to install EzSystemsPrivacyCookieBundle `v0.1`?

@andrerom This bundle (v0.2?) requires Symfony 2.6 because factory implementation method was changed (http://symfony.com/doc/current/components/dependency_injection/factories.html).

**Comment by bdunogier** [comment]
The requirement should be added to composer.json, then, @clash82, should it not ?

**Comment by clash82** [comment]
Yes, Symfony requirement should be added to composer.json - it's my fault. I'll do it today.

**Comment by andrerom** [comment]
thanks @clash82, please update any other requirements you maybe have before we tag v0.2

**Comment by clash82** [comment]
PR (https://github.com/ezsystems/EzSystemsPrivacyCookieBundle/pull/5) with updated composer requirements is opened and ready for review.

**Comment by nlescure** [comment]
@clash82 I confirm, it works fine in v0.1. 
Does the PR #5 restore de compatibility with Sf 2.5 ?

**Comment by clash82** [comment]
> Do you plan to restore Sf 2.5 compatibility ?

I don't think so, but if you don't have any strong needs to extend privacy-cookie-bundle you should stay with v0.1 - from the user point of view it works much the same way.

**Comment by bdunogier** [comment]
How much work would it require, @clash82 ? What 2.6 feature do you require
precisely ?

Maybe Nicolas could issue a PR if he's motivated... :-)

**Comment by clash82** [comment]
This bundle requires `setFactory()` method from `Sf 2.6` to work properly (http://symfony.com/doc/current/components/dependency_injection/factories.html).
I think "it's not much work". If @nlescure is motivated, I have nothing against that :-)

**Comment by andrerom** [comment]
The older api is deprecated, so I'm not sure we can support both at the same time.
Besides he is using Symfony 2.5, so he eventually needs to upgrade anyway as it is not supported anymore. Essentially this bundle can now only work with eZ Publish / Platform kernel 5.4.1 or higher

**Comment by nlescure** [comment]
I will try.

**Comment by andrerom** [comment]
Closing since composer.json was update avoiding this issue.
